pipeline{
    agent any
    stages{
        stage('build'){
            steps{
                sh "javac javaprogram/HelloWorld.java"
            }
        }
        stage('Run'){
            steps{
                sh "java -cp javaprogram HelloWorld"
            }
        }

    }
}
